// Generates src/lib/icons/generated.ts from scripts/icons-manifest.ts via @iconify-json/*.
// One export const per icon so bundlers can tree-shake; a single object would retain every glyph.
/// <reference types="node" />
import { getIconData, iconToSVG } from '@iconify/utils'
import type { IconifyJSON } from '@iconify/types'
import { readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { pathToFileURL } from 'node:url'
import * as custom from '../src/lib/icons/custom.ts'
import { iconify_icons } from './icons-manifest.ts'

const require_from_here = createRequire(import.meta.url)
const collections = new Map<string, IconifyJSON>()

const load_collection = async (prefix: string): Promise<IconifyJSON> => {
  const cached = collections.get(prefix)
  if (cached) return cached
  let path: string
  try {
    path = require_from_here.resolve(`@iconify-json/${prefix}/icons.json`)
  } catch {
    throw new Error(
      `Icon set '${prefix}' is not installed. Run: pnpm add -D @iconify-json/${prefix}`,
    )
  }
  const collection = JSON.parse(await readFile(path, `utf8`)) as IconifyJSON
  collections.set(prefix, collection)
  return collection
}

const single_path = /^<path(?<attrs>(?:\s+[a-z-]+="[^"]*")*)\s*\/>$/
const path_attr = /\s+(?<key>[a-z-]+)="(?<value>[^"]*)"/g
export const escape_template_literal = (value: string): string =>
  value.replaceAll(`\\`, `\\\\`).replaceAll(`\``, `\\\``).replaceAll(`\${`, `\\\${`)
const as_markup = (body: string) => `markup: \`${escape_template_literal(body)}\``

const as_shape = (body: string): string => {
  const attr_str = single_path.exec(body)?.groups?.attrs
  if (attr_str === undefined) return as_markup(body)
  const attrs: Record<string, string> = {}
  for (const { groups } of attr_str.matchAll(path_attr)) {
    if (groups?.key !== undefined && groups.value !== undefined)
      attrs[groups.key] = groups.value
  }
  const d = attrs.d
  if (
    !d ||
    Object.entries(attrs).some(
      ([key, value]) => key !== `d` && (key !== `fill` || value !== `currentColor`),
    )
  )
    return as_markup(body)
  return `d: \`${escape_template_literal(d)}\``
}

export const generate_icons = async (): Promise<void> => {
  const reserved = new Set(Object.keys(custom))
  const entries: string[] = []
  const problems: string[] = []

  for (const [name, icon_id] of Object.entries(iconify_icons)) {
    if (reserved.has(name)) {
      problems.push(`${name}: already exported from custom.ts`)
      continue
    }
    const [prefix, id] = icon_id.split(`:`)
    const collection = await load_collection(prefix)
    const data = getIconData(collection, id)
    if (!data) {
      problems.push(`${name}: '${icon_id}' not in @iconify-json/${prefix}`)
      continue
    }
    const { body, attributes } = iconToSVG(data, { height: `none` })
    // one line per glyph (same shape as custom.ts); trailing comment keeps the Iconify id greppable
    entries.push(
      `export const ${name} = { viewBox: \`${escape_template_literal(attributes.viewBox)}\`, ${as_shape(body.trim())} } satisfies IconData // ${icon_id}`,
    )
  }

  if (problems.length > 0) {
    throw new Error(`Bad manifest entries:\n  ${problems.join(`\n  `)}`)
  }

  const file = [
    `// GENERATED by scripts/generate-icons.ts — edit icons-manifest.ts and run \`pnpm gen:icons\`.`,
    `import type { IconData } from './types'`,
    ``,
    ...entries,
    ``,
  ].join(`\n`)

  const output_url = new URL(`../src/lib/icons/generated.ts`, import.meta.url)
  const current_file = await readFile(output_url, `utf8`).catch((error: unknown) => {
    if (error instanceof Error && `code` in error && error.code === `ENOENT`) return
    throw error
  })
  if (current_file === file) return
  await writeFile(output_url, file)
  console.info(
    `generated ${Object.keys(iconify_icons).length} icons from ${collections.size} sets`,
  )
}

const entry_path = process.argv[1]
if (entry_path && import.meta.url === pathToFileURL(entry_path).href)
  await generate_icons()
