name: Publish

on:
  push:
    tags:
      - v*.*.* # only trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Build and publish package
        run: |
          yarn
          yarn package
          yarn publish package
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
